/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImportsRouteImport } from './routes/imports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecipesRecipeIdRouteImport } from './routes/recipes/$recipeId'
import { Route as RecipesNewRouteImport } from './routes/recipes/new'
import { Route as RecipesRecipeIdIndexRouteImport } from './routes/recipes/$recipeId.index'
import { Route as RecipesRecipeIdEditRouteImport } from './routes/recipes/$recipeId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportsRoute = ImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdRoute = RecipesRecipeIdRouteImport.update({
  id: '/recipes/$recipeId',
  path: '/recipes/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesNewRoute = RecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdIndexRoute = RecipesRecipeIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecipesRecipeIdRoute,
} as any)
const RecipesRecipeIdEditRoute = RecipesRecipeIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => RecipesRecipeIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/imports': typeof ImportsRoute
  '/settings': typeof SettingsRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRouteWithChildren
  '/recipes/new': typeof RecipesNewRoute
  '/recipes/$recipeId/edit': typeof RecipesRecipeIdEditRoute
  '/recipes/$recipeId/': typeof RecipesRecipeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/imports': typeof ImportsRoute
  '/settings': typeof SettingsRoute
  '/recipes/new': typeof RecipesNewRoute
  '/recipes/$recipeId/edit': typeof RecipesRecipeIdEditRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/imports': typeof ImportsRoute
  '/settings': typeof SettingsRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRouteWithChildren
  '/recipes/new': typeof RecipesNewRoute
  '/recipes/$recipeId/edit': typeof RecipesRecipeIdEditRoute
  '/recipes/$recipeId/': typeof RecipesRecipeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/imports'
    | '/settings'
    | '/recipes/$recipeId'
    | '/recipes/new'
    | '/recipes/$recipeId/edit'
    | '/recipes/$recipeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/imports'
    | '/settings'
    | '/recipes/new'
    | '/recipes/$recipeId/edit'
    | '/recipes/$recipeId'
  id:
    | '__root__'
    | '/'
    | '/imports'
    | '/settings'
    | '/recipes/$recipeId'
    | '/recipes/new'
    | '/recipes/$recipeId/edit'
    | '/recipes/$recipeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImportsRoute: typeof ImportsRoute
  SettingsRoute: typeof SettingsRoute
  RecipesRecipeIdRoute: typeof RecipesRecipeIdRouteWithChildren
  RecipesNewRoute: typeof RecipesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imports': {
      id: '/imports'
      path: '/imports'
      fullPath: '/imports'
      preLoaderRoute: typeof ImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId': {
      id: '/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof RecipesRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/new': {
      id: '/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof RecipesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId/': {
      id: '/recipes/$recipeId/'
      path: '/'
      fullPath: '/recipes/$recipeId/'
      preLoaderRoute: typeof RecipesRecipeIdIndexRouteImport
      parentRoute: typeof RecipesRecipeIdRoute
    }
    '/recipes/$recipeId/edit': {
      id: '/recipes/$recipeId/edit'
      path: '/edit'
      fullPath: '/recipes/$recipeId/edit'
      preLoaderRoute: typeof RecipesRecipeIdEditRouteImport
      parentRoute: typeof RecipesRecipeIdRoute
    }
  }
}

interface RecipesRecipeIdRouteChildren {
  RecipesRecipeIdEditRoute: typeof RecipesRecipeIdEditRoute
  RecipesRecipeIdIndexRoute: typeof RecipesRecipeIdIndexRoute
}

const RecipesRecipeIdRouteChildren: RecipesRecipeIdRouteChildren = {
  RecipesRecipeIdEditRoute: RecipesRecipeIdEditRoute,
  RecipesRecipeIdIndexRoute: RecipesRecipeIdIndexRoute,
}

const RecipesRecipeIdRouteWithChildren = RecipesRecipeIdRoute._addFileChildren(
  RecipesRecipeIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImportsRoute: ImportsRoute,
  SettingsRoute: SettingsRoute,
  RecipesRecipeIdRoute: RecipesRecipeIdRouteWithChildren,
  RecipesNewRoute: RecipesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
