import type { StructuredRecipeLlm } from '@shared/types';

export const DEMO_IMPORT_URL =
  'https://www.archanaskitchen.com/restaurant-style-paneer-butter-masala-recipe';

export const DEMO_RECIPE_IMAGE_KEY = 'demo/paneer-butter-masala-hero.jpg';

export const demoStructuredRecipe: StructuredRecipeLlm = {
  title: 'Restaurant-Style Paneer Butter Masala',
  description:
    'A creamy North Indian paneer curry with a tomato-cashew gravy, Kashmiri chilli colour, and a finishing touch of kasuri methi. Perfect with hot roti or jeera rice.',
  yieldText: '4 servings',
  servings: 4,
  prepTimeMinutes: 20,
  cookTimeMinutes: 35,
  totalTimeMinutes: 55,
  cuisine: 'North Indian',
  dishName: 'Paneer Butter Masala',
  searchAliases: [
    'paneer butter masala',
    'butter paneer',
    'paneer makhani',
    'paneer curry',
  ],
  tags: ['indian', 'vegetarian', 'curry', 'weeknight', 'north-indian'],
  notes: 'Kashmiri chilli powder gives colour without too much heat. Soften the paneer in warm water for 10 minutes before cooking.',
  imageUrl: null,
  ingredients: [
    {
      originalText: '250 g paneer, cut into cubes',
      name: 'paneer',
      amount: 250,
      amountMax: null,
      unit: 'g',
      qualitative: null,
      preparation: 'cut into cubes',
      optional: false,
      pantryDefault: false,
      group: null,
    },
    {
      originalText: '30 g butter',
      name: 'butter',
      amount: 30,
      amountMax: null,
      unit: 'g',
      qualitative: null,
      preparation: null,
      optional: false,
      pantryDefault: false,
      group: null,
    },
    {
      originalText: '400 g ripe tomatoes, chopped',
      name: 'tomatoes',
      amount: 400,
      amountMax: null,
      unit: 'g',
      qualitative: null,
      preparation: 'chopped',
      optional: false,
      pantryDefault: false,
      group: null,
    },
    {
      originalText: '150 g onion, roughly chopped',
      name: 'onion',
      amount: 150,
      amountMax: null,
      unit: 'g',
      qualitative: null,
      preparation: 'roughly chopped',
      optional: false,
      pantryDefault: false,
      group: null,
    },
    {
      originalText: '15 g ginger-garlic paste',
      name: 'ginger-garlic paste',
      amount: 15,
      amountMax: null,
      unit: 'g',
      qualitative: null,
      preparation: null,
      optional: false,
      pantryDefault: false,
      group: null,
    },
    {
      originalText: '5 g Kashmiri chilli powder',
      name: 'Kashmiri chilli powder',
      amount: 5,
      amountMax: null,
      unit: 'g',
      qualitative: null,
      preparation: null,
      optional: false,
      pantryDefault: false,
      group: null,
    },
    {
      originalText: '3 g garam masala',
      name: 'garam masala',
      amount: 3,
      amountMax: null,
      unit: 'g',
      qualitative: null,
      preparation: null,
      optional: false,
      pantryDefault: false,
      group: null,
    },
    {
      originalText: '100 ml fresh cream',
      name: 'fresh cream',
      amount: 100,
      amountMax: null,
      unit: 'ml',
      qualitative: null,
      preparation: null,
      optional: false,
      pantryDefault: false,
      group: null,
    },
    {
      originalText: '2 g kasuri methi',
      name: 'kasuri methi',
      amount: 2,
      amountMax: null,
      unit: 'g',
      qualitative: null,
      preparation: null,
      optional: false,
      pantryDefault: false,
      group: null,
    },
    {
      originalText: '30 ml oil',
      name: 'oil',
      amount: 30,
      amountMax: null,
      unit: 'ml',
      qualitative: null,
      preparation: null,
      optional: false,
      pantryDefault: true,
      group: null,
    },
    {
      originalText: 'salt to taste',
      name: 'salt',
      amount: null,
      amountMax: null,
      unit: null,
      qualitative: 'to taste',
      preparation: null,
      optional: false,
      pantryDefault: true,
      group: null,
    },
    {
      originalText: 'fresh coriander leaves, for garnish',
      name: 'coriander leaves',
      amount: null,
      amountMax: null,
      unit: null,
      qualitative: 'for garnish',
      preparation: null,
      optional: true,
      pantryDefault: false,
      group: null,
    },
  ],
  instructions: [
    {
      text: 'Heat oil and butter in a kadai. Sauté onion until soft and lightly golden, then add ginger-garlic paste and cook until the raw smell disappears.',
    },
    {
      text: 'Add tomatoes, Kashmiri chilli powder, and salt. Cover and cook until the tomatoes break down into a thick masala.',
    },
    {
      text: 'Cool slightly, blend smooth with a splash of water, then strain back into the pan for a restaurant-style gravy.',
    },
    {
      text: 'Simmer the gravy, stir in cream and garam masala, then add paneer cubes and crushed kasuri methi. Cook 3–4 minutes and finish with coriander.',
    },
  ],
  inferredFields: ['tags', 'searchAliases', 'dishName', 'cuisine'],
};
